### ISSUE TITLE
Include a Makefile and an example

### ISSUE THREAD

**Issue by zorun** [angt/mud#3]
Hi,

This project looks interesting, however it is missing a Makefile :)

Also, as far as I can tell, it's meant to use as a library: can you provide an example program using the lib?  For instance, the one used to generate the performance results.

Thanks!

**Comment by angt** [comment]
Hi,
Thanks for your interest in this project :)
Mud is still very young and may change strongly in the future. However, you can take a look [here](https://github.com/angt/glorytun/tree/mud) to get an idea of ​​how you can integrate it.
Best regards.
