### ISSUE TITLE
Include support for simple XOR cipher.

### ISSUE THREAD

**Issue by lars18th** [angt/mud#4]
Hi,

Perhaps you found this stupid. But for a simple ofuscation and for testing the throughput I like to run it without encryption. That's with a fake XOR cipher.

The idea is: Maintain the current key exchange, but enhance the functions `mud_encrypt_opt()` and `mud_decrypt_opt()` for supporting a simple XOR, instead the default AES and the alternative ChaCha20.

What do you think?

**Comment by angt** [comment]
Our goal is to build a secure and easily usable protocol.
Adding an obfuscation XOR mode is not stupid but really dangerous.

Proposing the AES is already a concession for performance reasons.

**Comment by lars18th** [comment]
Hi @angt ,

> Adding an obfuscation XOR mode is not stupid but really dangerous.

I agree. So perhaps you can enable it _only_ when compiling in debug mode. That's when not in a release version.
