### ISSUE TITLE
Server doesn't stop sending on disconnected paths

### ISSUE THREAD

**Issue by bjornwein** [angt/mud#5]
Noticed this issue when testing glorytun for robustness in presences of total path failure.
It seems that mud_select_path() doesn't ignore empty path slots correctly, so return packets from the server will still be sent on removed paths.

This patch fixes the issue for me:
```
diff --git a/mud.c b/mud.c
index 4b24d12..cd6f9f7 100644
--- a/mud.c
+++ b/mud.c
@@ -358,7 +358,7 @@ mud_select_path(struct mud *mud, unsigned k)
     for (unsigned i = 0; i < mud->count; i++) {
         struct mud_path *path = &mud->paths[i];
 
-        if (!path->window)
+        if (path->state <= MUD_DOWN || !path->window)
             continue;
 
         window += ((path->window << 16) + (mud->window >> 1)) / mud->window;
```

**Comment by angt** [comment]
Thanks :)
I'll check that, a down path shouldn't have a window.
Regards

**Comment by bjornwein** [comment]
Thank you for your quick reply.
The path in question didn't pass MUD_DOWN, it went directly to MUD_EMPTY, and probably never got its window reset.

**Comment by angt** [comment]
Yes the concept of down path on server side doesn't really exist and empty path should not reply.
