### ISSUE TITLE
unable to bind server ip

### ISSUE THREAD

**Issue by ssdeol84** [angt/mud#7]
dear sir,

when ever i try to bind the server IP i get error:

glorytun bind 13.234.202.117 21 dev tun0 keyfile gt.key chacha &
[1] 3318
couldn't create mud

[1]+  Exit 1                  glorytun bind 13.234.202.117 21 dev tun0 keyfile gt.key chacha

please guide me what to do?

**Comment by angt** [comment]
Hello :)
You have to check that:
- You are `root`.
- The UDP port `21` is not already used with `ss`, `netstat`.
- The IP used is present with `ip addr`, `ifconfig`.

**Comment by ssdeol84** [comment]
Thanks sir can u send me video tutorial ?

**Comment by angt** [comment]
Sorry, I'm not a YouTuber :)

If you're not familiar with network and vpn setup,
I highly recommend you to use overthebox: https://github.com/ovh/overthebox
with the docker image: https://hub.docker.com/r/glorytun/server
or openMPTCProuter: https://www.openmptcprouter.com.
Both solutions package glorytun and configure it for you.

**Comment by ssdeol84** [comment]
I've install the glorytun on server.

On client side I've 3 usb 4G dongles and one wan port how I can combine the bandwidth at client side.

how the installation of glorytun to works on client side ?? Is there any other script for the client installation or same package will work on client side also? How we can do routing or connection configuration on client side.

**Comment by ssdeol84** [comment]
Thanks I've seen the installation page for client side installation. As I can see its all seems working. But is there any script by which we can make it run on boot itself. Bcoz after reboot client side I guess path will be drop and we need to do everything again for making both the path up.

**Comment by angt** [comment]
Great 👍 
The simplest way is to keep all the commands you've used (path, routing, etc) in a script, then launch it at startup after you started the `glorytun bind`.

**Comment by ssdeol84** [comment]
Can you give me sample script?

Sent from Yahoo Mail on Android 
 
  On Thu, Oct 1, 2020 at 12:15 AM, Adrien Gallouët<notifications@github.com> wrote:   


Great 👍
The simplest way is to keep all the commands you've used (path, routing, etc) in a script, then launch it at startup after you started the glorytun bind.

**Comment by ssdeol84** [comment]
Do we need bridge network on client side for connecting multiple 4G dongles

**Comment by ssdeol84** [comment]
On Both Side application is installed properly. 
I've allow opened port 55055 both udp and tcp and port 5000
but still its not listening

**Comment by angt** [comment]
Maybe this wiki will help you:
https://github.com/angt/glorytun/wiki/Using-Glorytun-with-2-ISP
