### ISSUE TITLE
ICMP Support?

### ISSUE THREAD

**Issue by utoni** [angt/mud#9]
I was wondering if ICMP support is possible.
Basicially, it should be possible w/o much effort as ICMP is also a datagram based protocol. I do not know (yet) if MTU/Path discovery and/or IP (de-)fragmentation will work out-of-the-box. By using raw sockets some of the socket options may also not work, unsure.
Or am I wrong?

What do you think about that?

**Comment by angt** [comment]
Hi,
An early version used ICMP with a raw socket, but often ICMP is blocked and it is not reliable.
Today, the MTU discovery does not use this mechanism anymore. It is slower but more robust.

**Comment by utoni** [comment]
> An early version used ICMP with a raw socket, but often ICMP is blocked and it is not reliable.

I am not sure if ICMP is often blocked. Any admin with some knowledge or experience probably would not do that. Do you have any source for that statement?

What do you mean by *not reliable* ? I mean UDP is also not *reliable* in terms of packet delivery. Or do you mean something else?

**Comment by angt** [comment]
No I mean, that many people had their tunnels broken because of the ICMP not working properly.
I had to remove this code and go to something more general to make it work.
